/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Notion-inspired color palette
        notion: {
          bg: "#ffffff",
          "bg-secondary": "#f7f6f3",
          "bg-tertiary": "#f1f1ef",
          text: "#37352f",
          "text-secondary": "#6f6e69",
          "text-tertiary": "#9b9a97",
          border: "#e9e9e7",
          "border-light": "#f1f1ef",
          accent: "#2383e2",
          "accent-light": "#e7f3ff",
          success: "#0f7b0f",
          "success-light": "#e6fffa",
          warning: "#d9730d",
          "warning-light": "#fef2e6",
          danger: "#e03e3e",
          "danger-light": "#ffeaea",
          purple: "#9065b0",
          "purple-light": "#f4f1f7",
          pink: "#ad1a72",
          "pink-light": "#f9ebf4",
          yellow: "#dfab01",
          "yellow-light": "#fef9e6",
          orange: "#d9730d",
          "orange-light": "#fef2e6",
          green: "#0f7b0f",
          "green-light": "#e6fffa",
          blue: "#2383e2",
          "blue-light": "#e7f3ff",
          red: "#e03e3e",
          "red-light": "#ffeaea",
        },
        gray: {
          25: "#fcfcfb",
          50: "#f9f9f8",
          100: "#f1f1ef",
          200: "#e9e9e7",
          300: "#dfdfdd",
          400: "#cdcccb",
          500: "#9b9a97",
          600: "#6f6e69",
          700: "#37352f",
          800: "#2f2e2a",
          900: "#1f1f1c",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        sans: [
          "ui-sans-serif",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Helvetica",
          "Apple Color Emoji",
          "Arial",
          "sans-serif",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
        ],
        mono: [
          "ui-monospace",
          "SFMono-Regular",
          "SF Mono",
          "Monaco",
          "Inconsolata",
          "Roboto Mono",
          "source-code-pro",
          "Menlo",
          "Consolas",
          "DejaVu Sans Mono",
          "monospace",
        ],
      },
      fontSize: {
        xs: ["12px", { lineHeight: "16px" }],
        sm: ["14px", { lineHeight: "20px" }],
        base: ["16px", { lineHeight: "24px" }],
        lg: ["18px", { lineHeight: "28px" }],
        xl: ["20px", { lineHeight: "28px" }],
        "2xl": ["24px", { lineHeight: "32px" }],
        "3xl": ["30px", { lineHeight: "36px" }],
        "4xl": ["36px", { lineHeight: "40px" }],
      },
      spacing: {
        18: "4.5rem",
        88: "22rem",
      },
      animation: {
        "fade-in": "fadeIn 0.2s ease-out",
        "slide-up": "slideUp 0.2s ease-out",
        "slide-down": "slideDown 0.2s ease-out",
        "scale-in": "scaleIn 0.15s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(8px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        slideDown: {
          "0%": { transform: "translateY(-8px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        scaleIn: {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
      },
      boxShadow: {
        notion: "rgba(15, 15, 15, 0.1) 0px 0px 0px 1px, rgba(15, 15, 15, 0.1) 0px 2px 4px",
        "notion-hover": "rgba(15, 15, 15, 0.1) 0px 0px 0px 1px, rgba(15, 15, 15, 0.2) 0px 3px 12px",
        "notion-active": "rgba(15, 15, 15, 0.15) 0px 0px 0px 1px, rgba(15, 15, 15, 0.15) 0px 2px 4px",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
